version: "3.8"

services:
   api:
    # image: api
    build: ./api
    ports:
      - 1337:1337
    volumes:
     - ./api:/api
    env_file:
      - ./.env
   db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    restart: always
